### ISSUE TITLE
2.2.0.008-SNAPSHOT does not install on DSM 6.1.3-15152 Update 8

### ISSUE THREAD

**Issue by jaghatei** [openhab/openhab-syno-spk#108]
I tried to install 2.2.0.008 yesterday on a ds214play with DSM 6.1.3-15152 Update 8.
By whatever reason the preinst and postinst routines are not called during installation procedure leaving the package dead. Calling these scripts manually after setting SYNOPKG_PKGNAME=openHAB2 and
SYNOPKG_PKGDEST=/volume1/\@appstore/openHAB2 did install openHAB2 successfully. So I assume this must be a problem in above DSM version package installer not calling / not finding the package installation scripts.
During deinstallation the preuninst and postuninst routines are called.
I have not found any hint in any log explaining this issue, only the absence of the preinst and postinst parts in openHAB2-installation.log.

**Comment by rkrausen** [comment]
Same problem here...
DS-916+
DSM 6.1.3-15152 Update 8

**Comment by loovanloon** [comment]
Same here on DS214 / DSM 6.1.3-15152 Update 8.  It installs, but the package can't be run.
![image](https://user-images.githubusercontent.com/25280600/32374144-c068ead2-c09c-11e7-9609-4166140956e2.png)

**Comment by SchoppAx** [comment]
Hi guys,

I will try to fix the issue this weekend.

**Comment by cniweb** [comment]
I think that's a problem with DSM 6.1. I can not test it because I only have DSM version 4.1 and 5.2.
@SchoppAx Can you please take a look at this?

**Comment by zhelyan** [comment]
same

```
 cat /var/log/openHAB2-start_stop.log
Start service
  call start.sh.
  FAILED (su)
Stop service.
  openHAB is not running
done.
Start service
  call start.sh.
  FAILED (su)
Stop service.
  openHAB is not running
done.
```

**Comment by SchoppAx** [comment]
The problem is the ${OH_USERDATA} variable. 
You can't use this var instead of ${SYNOPKG_PKGDEST}/userdata, because if the folder dosen't exists the installation later tries to access the non existing path.

I will create a PR with the rollback to ${SYNOPKG_PKGDEST}/userdata ;-)

**Comment by cniweb** [comment]
OK, I released a new version, try it, please.

**Comment by Starlordi** [comment]
Still not working, after installation I am not able to start the package.

**Comment by HyperCopy** [comment]
Same issue here... just tried with the new version...

**Comment by SchoppAx** [comment]
Ok, i forgot to set the rights if the userdata folder still is under @appstore.

For a quick fix you can create the folder userdata in your config folder (like public/openhab2 or smarthome/openhab2). If you select the home dir it has to work.

@cniweb why do we not create the folders (addons, conf and userdata) automatically?

**Comment by SchoppAx** [comment]
Please test this pre-release: https://github.com/SchoppAx/openhab-syno-spk/releases/download/2.2.0.008-SNAPSHOT/openHAB-2.2.0.008-SNAPSHOT-syno-noarch-0.001.spk

**Comment by jaghatei** [comment]
Yes the installation of the new snapshot is successful.

Issue seems to base on a file rights problem in scripts folder of pkg.
After setting executable bit for group and others on files in script folder of original pkg file installation works.
So I suppose that with update 8 Synology changed the way of installation from default with root to some other user, but keeps deinstallation done by root.
That is how it works:
-rwxr-xr-x 1 root root 15418 Nov  5 20:15 installer.sh
-rwxr-xr-x 1 root root    52 Nov  5 20:15 postinst
-rwxr-xr-x 1 root root    52 Nov  5 20:15 postuninst
-rwxr-xr-x 1 root root    52 Nov  5 20:15 postupgrade
-rwxr-xr-x 1 root root    76 Nov  5 20:15 preinst
-rwxr-xr-x 1 root root    52 Nov  5 20:15 preuninst
-rwxr-xr-x 1 root root    76 Nov  5 20:15 preupgrade
-rwxr-xr-x 1 root root    49 Nov  5 20:15 start-stop-status
-rwxr-xr-x 1 root root  3791 Nov  5 20:15 start-stop-status.sh

this is how it is provided in original snapshot after unpack to /var/packages/openHAB2/scripts:
-rwxr--r-- 1 root root 15418 Nov  5 20:15 installer.sh
-rwxr--r-- 1 root root    52 Nov  5 20:15 postinst
-rwxr--r-- 1 root root    52 Nov  5 20:15 postuninst
-rwxr--r-- 1 root root    52 Nov  5 20:15 postupgrade
-rwxr--r-- 1 root root    76 Nov  5 20:15 preinst
-rwxr--r-- 1 root root    52 Nov  5 20:15 preuninst
-rwxr--r-- 1 root root    76 Nov  5 20:15 preupgrade
-rwxr--r-- 1 root root    49 Nov  5 20:15 start-stop-status
-rwxr--r-- 1 root root  3791 Nov  5 20:15 start-stop-status.sh

with your new snapshot you already set the rigths to -rwxrwxrwx for all files in scripts folder.

**Comment by loovanloon** [comment]
Yes! Thank you, works like a charm. I cannot tell you how happy I am: just installed the package on my Syno, and copied all the addons, conf, and userdata map from my windows installation over to the syno-installation. Only had to install the bindings form the Paper UI again, and the complete installation now works on the syno.

Thank you @cniweb Christian and @SchoppAx ! For all your time and efforts.
(only add instruction about the USERDATA map to the instalation texts. I will make a new issue for that)

**Comment by Starlordi** [comment]
Hello, your pre-release worked fine for me, Thanks

**Comment by cniweb** [comment]
@jaghatei Is there still a problem here? Can we close the issue then?

**Comment by Starlordi** [comment]
only the pre-release: 

https://github.com/SchoppAx/openhab-syno-spk/releases/download/2.2.0.008-SNAPSHOT/openHAB-2.2.0.008-SNAPSHOT-syno-noarch-0.001.spk

worked. It needs to be updated on the download homepage....

**Comment by cniweb** [comment]
Ahh, OK, I replaced it.

**Comment by jaghatei** [comment]
can be closed.
