### ISSUE TITLE
2.0.0-beta2-DSM6-RC not starting via package manager

### ISSUE THREAD

**Issue by 7Bit** [openhab/openhab-syno-spk#22]
Hi there,

just installed the latest prerelease and it is not starting via package manager. The log is also empty, it just doesn't start. I am running a DS214Play with latest DSM6. 

Let me know if I can deliver any further information or log files.

**Comment by 7Bit** [comment]
Starting manually:

```
7Bit@DiskStation:/volume1/@appstore/OpenHAB$ ./start_runtime.sh
find: `server': No such file or directory
Launching the openHAB runtime...
./start_runtime.sh: line 22: logs/openhab.stdout: Permission denied
```

**Comment by cniweb** [comment]
Hi @7Bit,

can you look this:
`netstat -an | grep 5555`

Chris

**Comment by masto182** [comment]
I have the same issue it will not start via the package manager

**Comment by shagkie** [comment]
Same problem...won't start and the log file is empty.

**Comment by cniweb** [comment]
Hi,

can please look at your, if the port is not already in use 5555?
`netstat -an | grep 5555`

General DSM 6.0 ports:
https://www.synology.com/knowledgebase/DSM/tutorial/General/What_network_ports_are_used_by_Synology_services

Chris

**Comment by 7Bit** [comment]
Hi @cniweb,
 Port is not used:
`root@DiskStation:~# netstat -an | grep 5555
root@DiskStation:~#
`
The protocol / log is also empty.

**Comment by timwest73** [comment]
I have the same problem here. Package won't start. Nothing on 5555 and the log is empty. Did this get resolved?

**Comment by enricobaros** [comment]
Hi All, I'm new with openhab, but not new with eclipse/karaf/java by my job, and with home automation by home that is full knx equipped.

I'm trying to install openhab2-beta2 on my synology DSM6. It's installed, with java8 from syno, but after startup, nothing is running. I've the impression that the issue is a user right issue. Also I see that links of conf & user data & runtime folders (to public/openHAB2/..) have not been created except for addons folder :  

eric@NAS:/volume1/@appstore/OpenHAB$ ls -lrt
total 56
-rwxr-xr-x  1 openhab root   1132 Nov 17  2013 start_debug_runtime.sh
-rwxr-xr-x  1 openhab root     65 Nov 17  2013 stop_runtime.sh
-rwxr-xr-x  1 openhab root    930 Nov 17  2013 start_runtime.sh
-rwxrwxrwx  1 openhab users   122 Jan 12 09:52 start.sh
-rwxrwxrwx  1 openhab users    73 Jan 12 09:52 start_debug.sh
-rwxrwxrwx  1 openhab users    72 Jan 12 09:52 start_debug.bat
-rwxrwxrwx  1 openhab users   127 Jan 12 09:52 start.bat
-rwxrwxrwx  1 openhab users 11232 Feb  1 23:36 LICENSE.TXT
drwxrwxrwx  5 openhab users  4096 May 23 15:45 runtime
drwxrwxrwx  5 openhab users  4096 May 23 15:45 userdata
lrwxrwxrwx  1 openhab root     31 May 23 15:45 addons -> /volume1/public/OpenHAB2/addons
drwxr-xr-x  2 openhab users  4096 May 23 15:45 logs
drwxrwxrwx 11 openhab users  4096 May 23 16:17 conf

**Comment by igorrobertifoc** [comment]
I changed telnet port from 5555 to 9555 but the problem is the same

**Comment by cniweb** [comment]
Hi @enricobaros,

can you start `/volume1/@appstore/OpenHAB/start.sh` manually?

Chris

**Comment by cniweb** [comment]
OK, I changed it in the start-stop-status.sh script in the next release!

**Comment by cniweb** [comment]
Can you try [Release 2.0.0-beta3-DSM6](https://github.com/openhab/openhab-syno-spk/releases/tag/2.0.0-beta3-DSM6), please?
And it´s OK, then I can close this Issue?

**Comment by igorrobertifoc** [comment]
I start using the Synology interface and the status in "in excution" :)
But when I go to http://192.168.192.20:8082/ I didn t see anything. I waited aroud 3-4 minutes :( 
maybe another port?

**Comment by igorrobertifoc** [comment]
works on 8080. But it's very slow.. it take around 15 minutes. On bash start.sh it took 2-3 minutes

**Comment by igorrobertifoc** [comment]
restarted synology, but waiting time is around 15 minutes and not all is working

**Comment by igorrobertifoc** [comment]
now I stopped the service on synology interface.. and now it work on 8080:)

**Comment by enricobaros** [comment]
Hi Chris,

Yes, I could start manually and it was working.

Now, I just install the new release beta3 and it’s working (on port 8080) out of the box. But when I have a configurations folder on /volume1/public/OpenHAB2/configurations 
It’s no more working, while links were correctly done. And in the log I see this :

eric@NAS:/volume1/@appstore/OpenHAB2$ ls -lrt
total 52
-rwxr-xr-x  1 openhab2 root   1132 Nov 17  2013 start_debug_runtime.sh
-rwxr-xr-x  1 openhab2 root     65 Nov 17  2013 stop_runtime.sh
-rwxr-xr-x  1 openhab2 root    930 Nov 17  2013 start_runtime.sh
-rwxrwxrwx  1 openhab2 users   122 Jan 12 09:52 start.sh
-rwxrwxrwx  1 openhab2 users    73 Jan 12 09:52 start_debug.sh
-rwxrwxrwx  1 openhab2 users    72 Jan 12 09:52 start_debug.bat
-rwxrwxrwx  1 openhab2 users   127 Jan 12 09:52 start.bat
-rwxrwxrwx  1 openhab2 users 11232 May 22 00:54 LICENSE.TXT
drwxrwxrwx 11 openhab2 users  4096 Jun  9 00:31 conf
drwxrwxrwx  5 openhab2 users  4096 Jun  9 00:31 runtime
lrwxrwxrwx  1 openhab2 root     39 Jun  9 00:31 configurations -> /volume1/public/OpenHAB2/configurations
lrwxrwxrwx  1 openhab2 root     31 Jun  9 00:31 addons -> /volume1/public/OpenHAB2/addons
drwxrwxrwx  9 openhab2 users  4096 Jun  9 00:31 userdata
eric@NAS:/volume1/@appstore/OpenHAB2$ cd userdata
eric@NAS:/volume1/@appstore/OpenHAB2/userdata$ ls
cache  deploy  etc  generated-bundles  kar  logs  tmp
eric@NAS:/volume1/@appstore/OpenHAB2/userdata$ cd logs
eric@NAS:/volume1/@appstore/OpenHAB2/userdata/logs$ ls
events.log  openhab.log
eric@NAS:/volume1/@appstore/OpenHAB2/userdata/logs$ ls- lrt
-sh: ls-: command not found
eric@NAS:/volume1/@appstore/OpenHAB2/userdata/logs$ ls 
events.log  openhab.log
eric@NAS:/volume1/@appstore/OpenHAB2/userdata/logs$ more openhab.log
2016-06-08 23:31:24.563 [WARN ] [org.apache.felix.fileinstall        ] - /volume1/@appstore/OpenHAB2/addons does not exist, please create it.
2016-06-08 23:31:24.574 [WARN ] [org.apache.felix.fileinstall        ] - Root path does not exist: /volume1/@appstore/OpenHAB2/addons
 

It’s telling that the path /volume1/@appstore/OpenHAB2/addons is missing but it’s no true !

**Comment by cniweb** [comment]
That's correct, then:
/volume1/@appstore/OpenHAB2/addons is not a directory, this is a symbolic link to /volume1/public/OpenHAB2/addons
You must drop your addons in /volume1/public/OpenHAB2/addons

And I change the Port in INFO from Package to Port 8080!

**Comment by cniweb** [comment]
Hi @igorrobertifoc and @7Bit,

I released a new Package:
https://github.com/openhab/openhab-syno-spk/releases/tag/2.0.0-beta3-DSM6

Try please and give me feedback, then I can close this Issue.

Thanks

**Comment by 7Bit** [comment]
The new package itself did not fixed the issue. But after digging deeper in the start-stop-status scripts I realized my installed scripts were somehow not the scripts of thee beta3 release.

So I had to uninstall the package first, then do a clean reinstall. Now at least the package is startable and stoppable via the package manager. OpenHAB itself does not works, but that's another story and issue. This issue seems to be fixed if you do a clean uninstall and reinstall.
