### ISSUE TITLE
No Dirs in openHAB2 after install OpenHAB-2.1.0.005-syno-noarch-0.001.spk

### ISSUE THREAD

**Issue by HeikoB** [openhab/openhab-syno-spk#70]
After fresh install OpenHAB-2.1.0.005-syno-noarch-0.001.spk no dir structure created.
Second i restore my OH2 installation from backup and try to update it using OpenHAB-2.1.0.005-syno-noarch-0.001.spk - all dirs was removed from OH2 dir.

**Comment by cniweb** [comment]
I think the problem is the folders that are linked to the public folder. Should I create a package without these folders so that the original folders are used?

**Comment by EtroxTaran** [comment]
same problem here.
I tried to update and after the update process the openHab2 folder in volume1/@appstore/openHab2 only contains the startup Scripts but nothing more.
And openHab is not installed anymore.
I tried removing the package removing the public folders....
But nothing works.

**Comment by cniweb** [comment]
I released a new version:
https://github.com/openhab/openhab-syno-spk/releases/tag/2.1.0.006
Can you try it, please.

Thanks,
Chris

**Comment by bcrippsy38** [comment]
Hi Chris, I still have the same issue. As well as not being able to connect to the url. not even sure its really running after install

**Comment by cniweb** [comment]
Sorry, wrong Download location.
New release:
https://github.com/openhab/openhab-syno-spk/releases/tag/2.1.0.007

**Comment by divinebovine** [comment]
I am having the same problems as well. I have tried 2.1.0.008 and 2.2.0.002-SNAPSHOT.

**Comment by Elle4u** [comment]
Same here. I think there is an error in the installer. My old installation got deleted and from the new installation only the 3 start/stop-scripts are there.

This installer is working:
openHAB-2.0.0.001-DSM6-syno-noarch-0.001.spk

Tried the download-link manually and there is no such file.
Edit; OK. New version with corrected url. -> Damn. Still not working (openHAB-2.1.0.008-syno-noarch-0.001.spk)

**Comment by cniweb** [comment]
New releases:
https://github.com/openhab/openhab-syno-spk/releases/tag/2.1.0.005-DSM6

**Comment by cniweb** [comment]
The folder creation work with the new release.
Can we close this issue?

**Comment by bcrippsy38** [comment]
I actually had a question on that. So the latest release installed fine and generated the conf directories in public. the problem I'm having is it doesn't appear any setting or things are being saved in those directories. only readme files are contained in those folders.

**Comment by SchoppAx** [comment]
Hi @bcrippsy38,

can you please look at your `openhab.log` located in `/{yourvolume}/@appstore/openHAB2/logs`, are there any permission errors?

_Please note, that only the configuration files for openhab1 bindings will be created in the public conf folders. Openhab2 bindings will be saved in the `/{yourvolume}/@appstore/openHAB2/userdata/...` folder. So if you have only openhab2 bindings installed, your public conf folders only contains readme files._

**Comment by bcrippsy38** [comment]
Hi @SchoppAx,
that makes sense, I am new to openhab (if its not obvious) and only have bindings in openhab2 i'm assuming. no permission errors in log files

**Comment by cniweb** [comment]
@bcrippsy38 OK, now can we close this issue?

**Comment by bcrippsy38** [comment]
Yes I think its resolved
